hearings/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^personal_page/$', 'hearings.views.personal_page', name='personal_page'),
    url(r'^recap/$', 'hearings.views.recap', name='recap'),
    url(r'^teacher/$', 'hearings.views.teacher', name='teacher'),
                       
    url(r'^parent/$', 'hearings.views.parent', name='parent'),
    url(r'^book_appointment/(?P<id>[0-9]+)?$', 'hearings.views.book_appointment', name='book_appointment'),
    url(r'^save_appointment/(?P<tid>[0-9]+)/(?P<aid>[0-9]+)/$', 'hearings.views.save_appointment', name='save_appointment'),
    url(r'^cancel_appointment/(?P<id>[0-9]+)/$', 'hearings.views.cancel_appointment', name='cancel_appointment'),
    url(r'^single_availability/(?P<id>[0-9]+)?$', 'hearings.views.single_availability', name='single_availability'),
    url(r'^global_availabilities/$', 'hearings.views.global_availabilities', name='global_availabilities'),
    url(r'^delete_availability/(?P<id>[0-9]+)?$', 'hearings.views.delete_availability', name='delete_availability'),
)

pyhearing/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import django.contrib.auth.views as aviews

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pyhearing.views.home', name="home"),
    url(r'^login/$', 'pyhearing.views.login_view', name="login"),
    url(r'^logout/$', 'pyhearing.views.logout_view', name="logout"),
    url(r'^mass_mail/$', 'pyhearing.views.mass_mail', name='mass_mail'),

    url(r'^hearings/', include('hearings.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^user/password/change/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'password_change_form.html'},
        name="password_change"),
    url(r'^user/password/change/done/$', aviews.password_change_done,
        {'template_name': 'password_change_done.html'}),
    url(r'^user/password/reset/$', aviews.password_reset,
        {'post_reset_redirect' : '/user/password/reset/done/',
        'template_name': 'password_reset_form.html'},
        name="password_reset"),
    url(r'^user/password/reset/done/$',
        aviews.password_reset_done,
        {'template_name': 'password_reset_done.html'}),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        aviews.password_reset_confirm,
        {'post_reset_redirect' : '/user/password/done/',
        'template_name': 'password_reset_confirm.html'}),
    url(r'^user/password/done/$', aviews.password_reset_complete,
        {'template_name': 'password_reset_complete.html'}),
)

hearings/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.mail import send_mail
from django.conf import settings
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context


class SchoolClass(models.Model):
    name = models.CharField(max_length=16, unique=True)

    class Meta:
        verbose_name_plural = "School classes"
        ordering = ('name',)

    def __unicode__(self):
        return self.name

class Teacher(models.Model):
    user = models.ForeignKey(User, null=False, blank=False,
                             related_name="as_teacher")
    school_class = models.ForeignKey(SchoolClass, null=False, blank=False,
                                     related_name='teachers')
    subject_taught = models.CharField(max_length=1024)

    def __unicode__(self):
        return "%s %s - %s" % (self.user.first_name, self.user.last_name, self.school_class)

    def get_full_name(self):
        return self.user.get_full_name()

    def can_add_appointment(self):
        availabilities = self.user.availability.all()
        for av in availabilities:
            if av.can_add_appointment():
                return True
        return False

    def send_teacher_reminder(self, appointments):
        message = """
Gent. %s %s,

le ricordiamo i suoi appuntamenti prenotati per le udienze previste
per la giornata di domani:

""" % (self.user.first_name, self.user.last_name)
        
        for a in appointments:
            message += "%s: dalle %s alle %s\n" % (a.parent, a.when.start, a.when.end)

        message += "\nLe auguriamo buon lavoro.\n"
        message = "%s\n\n%s" % (message, settings.NOTIFICATION_EMAIL_SIGNATURE)
        if self.user.email:
            send_mail(settings.NOTIFICATION_EMAIL_SUBJECT,
                      message,
                      settings.NOTIFICATION_EMAIL_FROM,
                      [self.user.email])

class Parent(models.Model):
    user = models.ForeignKey(User, null=False, blank=False,
                             related_name="as_parent")
    school_class = models.ForeignKey(SchoolClass, null=False, blank=False,
                                     related_name='parents')
    class Meta:
        unique_together = ('user', 'school_class')
        
    def get_teachers_appointments(self):
        teachers = []
        for appointment in self.appointments_as_parent.all().filter(when__day__gte=date.today()):
            teachers.append(appointment.when.teacher)
        return teachers

    def get_availabilities_appointments(self):
        availabilities = []
        for appointment in self.appointments_as_parent.all().filter(when__day__gte=date.today()):
            availabilities.append(appointment.when)
        return availabilities

    def __unicode__(self):
        return "%s %s - %s" % (self.user.first_name, self.user.last_name,
                               self.school_class)

    def get_full_name(self):
        return self.user.get_full_name()


class Availability(models.Model):
    teacher = models.ForeignKey(User, null=False, blank=False,
                                related_name="availability")
    day = models.DateField(verbose_name=_("Day"))
    start = models.TimeField(verbose_name=_("Start time"))
    end = models.TimeField(verbose_name=_("End Time"))
    max_visits = models.IntegerField(verbose_name=_("Max appointments"))

    class Meta:
        verbose_name_plural = "Availabilities"
        ordering = ('day', 'start')

    def get_free_slots(self):
        return self.max_visits - self.appointments.all().count()

    def can_add_appointment(self):
        return True if self.get_free_slots() > 0 else False

    def __unicode__(self):
        return "%s - %s (%s - %s)" % (self.teacher,
                                      self.day,
                                      self.start, self.end)

    def _send_boss_email(self, message):
        message = "%s\n\n%s" % (message, settings.NOTIFICATION_EMAIL_SIGNATURE)
        if settings.NOTIFICATION_BOSS_EMAIL:
            send_mail(settings.NOTIFICATION_BOSS_SUBJECT,
                      message,
                      settings.NOTIFICATION_EMAIL_FROM,
                      [settings.NOTIFICATION_BOSS_EMAIL])

    def send_boss_delete(self):
        message = """
Il docente %s ha annullato le udienze previste per il giorno
%s dalle ore %s alle ore %s.
        """ % (self.teacher, self.day,
               self.start, self.end)
        
        self._send_boss_email(message)
    
@receiver(post_delete, sender=Availability)
def notify_boss_delete(sender, **kwargs):
    kwargs['instance'].send_boss_delete()


class Appointment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    teacher = models.ForeignKey(Teacher, null=False, blank=False,
                                related_name="appointments_as_teacher")
    parent = models.ForeignKey(Parent, null=False, blank=False,
                               related_name="appointments_as_parent")
    when = models.ForeignKey(Availability, null=False, blank=False,
                             related_name="appointments")

    @property
    def iso_timestamp(self):
        return "%sT%s+01:00" % (
            self.when.day.strftime("%Y-%m-%d"),
            self.when.start.strftime("%H:%M:%S")
            )
    
    class Meta:
        ordering = ('created', 'teacher', 'parent', 'when')

    def __unicode__(self):
        return "%s - %s - %s - %s" % (self.parent, self.teacher,
                                      self.when.day, self.when.start)

    def send_boss_notification(self, action):
        message = """

        """

        
    def send_parent_delete(self):
        message = """
Gent. %s,

La informiamo che il suo appuntamento per il giorno %s
con il docente %s e' stato annullato.

Cordiali saluti

""" % (
            self.parent,
            self.when.day.strftime("%d/%m/%Y"),
            self.teacher
            )
        self._send_parent_email(message)


    def send_parent_updates(self):
        message = """
Gent. %s,

La informiamo che il suo appuntamento e' stato modificato,
di seguito i nuovi dettagli.

Nuovo appuntamento per il giorno giorno %s
dalle ore %s alle ore %s, con il nostro docente %s.

Cordiali saluti

""" % (
            self.parent,
            self.when.day.strftime("%d/%m/%Y"),
            str(self.when.start)[:5],
            str(self.when.end)[:5],
            self.teacher
            )
        self._send_parent_email(message)

    def send_parent_created(self):
        plaintext = get_template("hearings/parent_reminder.txt")
        htmltext = get_template("hearings/parent_reminder.html")
        ctx = dict(parent=self.parent,
                   when=self.when,
                   teacher=self.teacher,
                   appointment=self)
        d = Context(ctx)

        if self.parent.user.email:
            subject = settings.NOTIFICATION_EMAIL_SUBJECT
            from_email = settings.NOTIFICATION_EMAIL_FROM
            to = self.parent.user.email
            text_content = plaintext.render(d)
            html_content = htmltext.render(d)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
                                     

    def send_parent_reminder(self):
        message = """
Gent. %s,

Le ricordiamo il suo appuntamento per il giorno %s
dalle ore %s alle ore %s, con il nostro docente %s.

Cordiali saluti

""" % (
            self.parent,
            self.when.day.strftime("%d/%m/%Y"),
            str(self.when.start)[:5],
            str(self.when.end)[:5],
            self.teacher
            )
        self._send_parent_email(message)


    def _send_parent_email(self, message):
        message = "%s\n\n%s" % (message, settings.NOTIFICATION_EMAIL_SIGNATURE)
        if self.parent.user.email:
            send_mail(settings.NOTIFICATION_EMAIL_SUBJECT,
                      message,
                      settings.NOTIFICATION_EMAIL_FROM,
                      [self.parent.user.email])

@receiver(post_save, sender=Appointment)
def notify_updates(sender, **kwargs):
    if kwargs.get('created'):
        kwargs['instance'].send_parent_created()
    else:
        kwargs['instance'].send_parent_updates()

@receiver(post_delete, sender=Appointment)
def notify_delete(sender, **kwargs):
    kwargs['instance'].send_parent_delete()

hearings/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext_lazy as _
import hearings.models as hmodels


class SingleAvailabilityForm(forms.ModelForm):
    class Meta:
        model = hmodels.Availability
        exclude = ('teacher',)

    def __init__(self, *args, **kwargs):
        super(SingleAvailabilityForm, self).__init__(*args, **kwargs)
        self.fields['day'] = forms.DateField(error_messages={'required': _("You have to insert the day")})

    def clean(self):
        cleaned_data = super(SingleAvailabilityForm, self).clean()
        start = cleaned_data.get('start', None)
        end = cleaned_data.get('end', None)
        if start and end and start >= end:
            msg = _("Start cannot be after end")
            self._errors['start'] = forms.util.ErrorList([msg])
            self._errors['end'] = forms.util.ErrorList([msg])
            del self.cleaned_data['start']
            del self.cleaned_data['end']
        return self.cleaned_data


class GlobalAvailabilitiesForm(forms.Form):
    first_day = forms.DateField(label=_("Date from"))
    last_day = forms.DateField(label=_("Date to"))
    day = forms.ChoiceField(label=_("Day of week"),
                            choices=(
        (0, _('Monday')),
        (1, _('Tuesday')),
        (2, _('Wednesday')),
        (3, _('Thursday')),
        (4, _('Friday')),
        (5, _('Saturday')),
        #(6, _('Sunday')),
    ))
    start = forms.TimeField(label=_("Start time"))
    end = forms.TimeField(label=_("End time"))
    max_visits = forms.IntegerField(label=_("Max appointments"))

    def clean(self):
        cleaned_data = super(GlobalAvailabilitiesForm, self).clean()
        first_day = cleaned_data.get('first_day', None)
        last_day = cleaned_data.get('last_day', None)
        start = cleaned_data.get('start', None)
        end = cleaned_data.get('end', None)
        # Check days...
        if first_day and last_day and first_day > last_day:
            msg = _("First day cannot be after last day")
            self._errors['first_day'] = forms.util.ErrorList([msg])
            self._errors['last_day'] = forms.util.ErrorList([msg])
            del self.cleaned_data['first_day']
            del self.cleaned_data['last_day']
        # Check times...
        if start and end and start > end:
            msg = _("Start cannot be after end")
            self._errors['start'] = forms.util.ErrorList([msg])
            self._errors['end'] = forms.util.ErrorList([msg])
            del self.cleaned_data['start']
            del self.cleaned_data['end']
        return self.cleaned_data

hearings/templates/hearings/book_appointment.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Parent" %}{% endblock title %}

{% block content %}
<div class="row">
  <h4>{% trans "Teacher" %}: {{teacher.get_full_name}}</h4>
  {% if availabilities %}
    <table class="table">
      <thead>
        <tr>
          <th>{% trans "Day" %}</th>
          <th>{% trans "Hour" %}</th>
          <th>{% trans "Book" %}</th>
        </tr>
      </thead>
      <tbody>
    {% for availability in availabilities %}
      <tr>
        <td>{{availability.day|date:"l d/m/Y"|capfirst}}</td>
        <td>{{availability.start|date:"H:i"}} - {{availability.end|date:"H:i"}}</td>
        {% if availability in parent.get_availabilities_appointments %}
        <td>{% trans "Already booked" %}</td>
        {% elif not availability.can_add_appointment %}
        <td>{% trans "No booking possible, please choose another day" %}</td>
        {% else %}
        <td>
          <a class="btn" href="{% url 'save_appointment' tid=teacher.id aid=availability.id %}"
            onclick="if (!confirm('Are you sure?')) return false;">{% trans "Book" %}
          </a>
        </td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    {% trans "No availabilities" %}
  {% endif %}
</div>
{% endblock content %}

hearings/templates/hearings/global_availabilities.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Teacher" %}{% endblock title %}

{% block head_resources %}
<link href="{{STATIC_URL}}css/datepicker.css" rel="stylesheet"/>
<link href="{{STATIC_URL}}css/bootstrap-spinedit.css" rel="stylesheet"/>
<link href="{{STATIC_URL}}css/bootstrap-timepicker.min.css" rel="stylesheet"/>
<script src="{{STATIC_URL}}js/bootstrap-timepicker.min.js"></script>
<script src="{{STATIC_URL}}js/bootstrap-datepicker.js"></script>
<script src="{{STATIC_URL}}js/bootstrap-spinedit.js"></script>

<script type="text/javascript">
    $(function() {
        $('#id_first_day').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            startDate: new Date(),
            weekStart: 1,
            daysOfWeekDisabled: [0],
            todayHighlight: true,
        });
        $('#id_last_day').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            startDate: new Date(),
            weekStart: 1,
            daysOfWeekDisabled: [0],
            todayHighlight: true,
        });
        $('#id_max_visits').spinedit({
            minimum: 1,
            maximum: 20,
        });
        var timepicker_conf = {
            Minutestep: 5,
            showSeconds: false,
            showMeridian: false,
        }
        $('#id_start').addClass("input-small");
        $('#id_end').addClass("input-small");
        $('#id_start').timepicker(timepicker_conf);
        $('#id_end').timepicker(timepicker_conf);

    });
</script>
{% endblock head_resources  %}

{% block content %}

<form method="post" action="{{request.get_full_path}}" class="form-horizontal">
  {% csrf_token %}
  <div class="control-group">
    <label class="control-label"
           for="id_day">{{form.first_day.label}}</label>
      <div class="controls">{{form.first_day.errors}}
      {{form.first_day}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_day">{{form.last_day.label}}</label>
    <div class="controls">{{form.last_day.errors}}
      {{form.last_day}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_day">{{form.day.label}}</label>
    <div class="controls">
      {{form.day}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_start">{{form.start.label}}</label>
      <div class="controls">{{form.start.errors}}
      <div class="input-append bootstrap-timepicker">
        {{form.start}}
        <span class="add-on">
          <i class="icon-time"></i>
        </span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_end">{{form.end.label}}</label>
    <div class="controls">{{form.end.errors}}
      <div class="input-append bootstrap-timepicker">
        {{form.end}}
        <span class="add-on">
          <i class="icon-time"></i>
        </span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_max_visits">{{form.max_visits.label}}</label>
    <div class="controls">
      {{form.max_visits}}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
  </div>
</form>

{% endblock content %}

hearings/templates/hearings/parent.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Parent" %}{% endblock title %}

{% block content %}
<h4>{% trans "Parent:"%} {{parent.get_full_name}}</h4>
{% if teachers %}
<h4>{% trans "Teacher(s):"%}</h4>
<table class="table">
  <thead>
    <tr>
      <th>{% trans "Teacher" %}</th>
      <th>{% trans "Class" %}</th>
      <th>{% trans "Subject taught" %}</th>
      <th>{% trans "Book an appointment" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for teacher in teachers %}
    <tr>
      <td>{{teacher.get_full_name}}</td>
      <td>{{teacher.school_class}}</td>
      <td>{{teacher.subject_taught}}</td>
      {% if teacher.can_add_appointment %}
      <td><a class="btn" href="{% url 'book_appointment' id=teacher.id %}"><i class="icon-thumbs-up"></i></a></td>
      {% else %}
      <td>{% trans "All booked" %}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>{% trans "Your user have no classes or teachers. You can't book an appointment." %}</p>
<p>{% trans "Please contact our school to handle this issue." %}</p>
{% endif %}
<h4>{% trans "Next booked appointments:"%}</h4>
{% if appointments %}
<table class="table">
  <thead>
    <tr>
      <th>{% trans "Teacher" %}</th>
      <th>{% trans "Class" %}</th>
      <th>{% trans "When" %}</th>
      <th>{% trans "Cancel" %}</th>
    </tr>
  </thead>
  <tbody>
  {% for appointment in appointments %}
  <tr>
    <td>{{appointment.teacher.get_full_name}}</td>
    <td>{{appointment.parent.school_class}}</td>
    <td>{{appointment.when.day|date:"l d/m/Y"|capfirst}}, {{appointment.when.start|date:"H:i"}}</td>
    <td>
      <a class="btn btn-danger" href="{% url 'cancel_appointment' id=appointment.id %}"
        onclick="if (!confirm('Are you sure?')) return false;"><i class="icon-remove"></i>
      </a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
{% trans "No appointments" %}
{% endif %}
{% endblock content %}

hearings/templates/hearings/parent_reminder.html
<html>
  <body>
    <script type="application/ld+json">
      {
      "@context": "http://schema.org",
      "@type": "EventReservation",
      "reservationNumber": "{{appointment.id}}",
      "reservationStatus": "http://schema.org/Confirmed",
      "underName": {
      "@type": "Person",
      "name": "{{parent}}"
      },
      "reservationFor": {
      "@type": "Event",
      "name": "Colloquio con {{teacher}}",
      "startDate": "{{appointment.iso_timestamp}}",
      "location": {
      "@type": "Place",
      "name": "Liceo Torricelli",
         "address": {
            "@type":           "PostalAddress",
            "streetAddress":   "Via La solita",
            "addressLocality": "Bolzano",
            "addressRegion":   "BZ",
            "postalCode":      "39100",
            "addressCountry":  "IT"
          }
      }
      }
      }
    </script>
    <h1>Prenotazione confermata</h1>
    <p>Gent. {{parent}},</p>

    <p>le confermiamo la sua prenotazione per il giorno {{when.day|date}}
      dalle ore {{when.start}} alle ore {{when.end}}, con la/il docente {{teacher}}</p>

    <p>Cordiali saluti!</p>
  </body>
</html>

hearings/templates/hearings/personal_page.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Personal page" %}{% endblock title %}

{% block content %}
{% if user.as_teacher.count %}
<h4>{% trans "You are teacher in these classes:" %}</h4>
<ul>
{% for t in user.as_teacher.all %}
<li>{{t.school_class}} ({{t.subject_taught}})</li>
{% endfor %}
</ul>
<a class="btn" href="{% url 'teacher' %}">{% trans "Go to your teacher profile page" %}</a>
{% endif %}

{% if user.as_parent.count %}
<h4>{% trans "You are a parent of student(s) in these classes:" %}</h4>
<ul>
  {% for p in user.as_parent.all %}
  <li>{{p.school_class}}</li>
  {% endfor %}
</ul>
<a class="btn" href="{% url 'parent' %}">{% trans "Go to your parent profile page" %}</a>
{% endif %}

{% endblock content %}

hearings/templates/hearings/recap.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "All appointments for" %} {{requested_date|date}}</h1>
<table class="table table-condensed">
  <tr>
    <th>{% trans "Teacher" %}</th>
    <th>{% trans "Class" %}</th>
    <th>{% trans "Parent" %}</th>
    <th>{% trans "Time" %}</th>
  </tr>
  {% for a in appointments %}
  <tr>
    <td>{{a.teacher.user.first_name}} {{a.teacher.user.last_name}}</td>
    <td>{{a.teacher.school_class}}</td>
    <td>{{a.parent}}</td>
    <td>{{a.when.day}} - {{a.when.start}} / {{a.when.end}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

hearings/templates/hearings/single_availability.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Teacher" %}{% endblock title %}

{% block head_resources %}
<link href="{{STATIC_URL}}css/datepicker.css" rel="stylesheet"/>
<link href="{{STATIC_URL}}css/bootstrap-spinedit.css" rel="stylesheet"/>
<link href="{{STATIC_URL}}css/bootstrap-timepicker.min.css" rel="stylesheet"/>
<script src="{{STATIC_URL}}js/bootstrap-timepicker.min.js"></script>
<script src="{{STATIC_URL}}js/bootstrap-datepicker.js"></script>
<script src="{{STATIC_URL}}js/bootstrap-spinedit.js"></script>

<script type="text/javascript">
  $(function() {
    $('#id_day').datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      startDate: new Date(),
      weekStart: 1,
      daysOfWeekDisabled: [0],
      todayHighlight: true,
    });
    $('#id_max_visits').spinedit({
      minimum: 1,
      maximum: 20,
    });
  var timepicker_conf = {
  minuteStep: 5,
  showSeconds: false,
  showMeridian: false,
  }
  $('#id_start').addClass("input-small");
  $('#id_end').addClass("input-small");
  $('#id_start').timepicker(timepicker_conf);
  $('#id_end').timepicker(timepicker_conf);

  });
</script>
{% endblock head_resources  %}

{% block content %}
<form method="post" action="{{request.get_full_path}}" class="form-horizontal">
  {% csrf_token %}

  <div class="control-group">
    <label class="control-label"
           for="id_day">{{form.day.label}}</label>
      <div class="controls">{{form.day.errors}}
      {{form.day}}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"
           for="id_start">{{form.start.label}}</label>
    <div class="controls">{{form.start.errors}}
      <div class="input-append bootstrap-timepicker">
        {{form.start}}
        <span class="add-on">
          <i class="icon-time"></i>
        </span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_end">{{form.end.label}}</label>
    <div class="controls">{{form.end.errors}}
      <div class="input-append bootstrap-timepicker">
        {{form.end}}
        <span class="add-on">
          <i class="icon-time"></i>
        </span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label"
           for="id_max_visits">{{form.max_visits.label}}</label>
    <div class="controls">
      {{form.max_visits}}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
  </div>
</form>



{% endblock content %}